In [1]:
import pandas as pd
import numpy as np
import scanpy as sc
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from scipy.spatial.distance import cdist
import torch.nn.functional as F

In [32]:
adata = sc.read_h5ad('../example.h5ad')

step1. ensuring the spot x,y are absoulte distance

In [3]:
#for visium data
adata.obs['X'] = adata.obs['array_row'] *100
adata.obs['Y'] = adata.obs['array_col'] *100
adata.obs

                    in_tissue  array_row  array_col  n_counts     X      Y
AAACAAGTATCTCCCA-1          1         50        102    5625.0  5000  10200
AAACACCAATAACTGC-1          1         59         19    9159.0  5900   1900
AAACAGAGCGACTCCT-1          1         14         94    2660.0  1400   9400
AAACAGGGTCTATATT-1          1         47         13    9020.0  4700   1300
AAACAGTGTTCCTGGG-1          1         73         43    9714.0  7300   4300
...                       ...        ...        ...       ...   ...    ...
TTGTTGTGTGTCAAGA-1          1         31         77    7260.0  3100   7700
TTGTTTCACATCCAGG-1          1         58         42    7510.0  5800   4200
TTGTTTCATTAGTCTA-1          1         60         30    5742.0  6000   3000
TTGTTTCCATACAACT-1          1         45         27   20118.0  4500   2700
TTGTTTGTATTACACG-1          1         73         41    8169.0  7300   4100

[2640 rows x 6 columns]

In [34]:
adata.obs

,in_tissue,array_row,array_col,n_counts,X,Y,tcr,cell_type
AAACAAGTATCTCCCA-1,1,50,102,5625.0,5000,10200,1,1
AAACACCAATAACTGC-1,1,59,19,9159.0,5900,1900,1,0
AAACAGAGCGACTCCT-1,1,14,94,2660.0,1400,9400,0,1
AAACAGGGTCTATATT-1,1,47,13,9020.0,4700,1300,1,1
AAACAGTGTTCCTGGG-1,1,73,43,9714.0,7300,4300,0,0
...,...,...,...,...,...,...,...,...
TTGTTGTGTGTCAAGA-1,1,31,77,7260.0,3100,7700,0,1
TTGTTTCACATCCAGG-1,1,58,42,7510.0,5800,4200,1,1
TTGTTTCATTAGTCTA-1,1,60,30,5742.0,6000,3000,1,1
TTGTTTCCATACAACT-1,1,45,27,20118.0,4500,2700,0,1
TTGTTTGTATTACACG-1,1,73,41,8169.0,7300,4100,1,0

In [35]:
adata.write_h5ad('../example.h5ad')

step2 if there is not cell type in the h5ad intergrate cell type

In [12]:
cell_type = pd.read_csv('../annotation.txt', sep='\t',index_col=0)
cell_type

                       cell_type  cluster            X             Y    T_mean
ID
s_016um_00052_00082-1  Non-Tumor       10  5307.678917  12449.199920 -0.173486
s_016um_00010_00367-1      Tumor        0  6040.988191  16999.787109 -0.115027
s_016um_00163_00399-1  Non-Tumor       23  3599.047921  17543.405848  1.293282
s_016um_00238_00388-1  Non-Tumor       21  2396.768054  17382.861868 -0.173486
s_016um_00144_00175-1  Non-Tumor        1  3855.484646  13956.137643 -0.091925
...                          ...      ...          ...           ...       ...
s_016um_00375_00231-1  Non-Tumor        9   172.852112  14900.346458 -0.173486
s_016um_00109_00223-1  Non-Tumor       18  4425.694211  14716.500350 -0.088819
s_016um_00039_00175-1  Non-Tumor       12  5535.624672  13933.920353 -0.173486
s_016um_00037_00193-1  Non-Tumor       10  5571.488924  14221.434174 -0.173486
s_016um_00144_00329-1     T cell        3  3888.206480  16419.520351 -0.007385

[137051 rows x 5 columns]

In [13]:
cell_type['cell_type'] = [1 if x == 'Tumor' else 2 if x == 'T cell' else 0 for x in cell_type['cell_type']]
cell_type

                       cell_type  cluster            X             Y    T_mean
ID
s_016um_00052_00082-1          0       10  5307.678917  12449.199920 -0.173486
s_016um_00010_00367-1          1        0  6040.988191  16999.787109 -0.115027
s_016um_00163_00399-1          0       23  3599.047921  17543.405848  1.293282
s_016um_00238_00388-1          0       21  2396.768054  17382.861868 -0.173486
s_016um_00144_00175-1          0        1  3855.484646  13956.137643 -0.091925
...                          ...      ...          ...           ...       ...
s_016um_00375_00231-1          0        9   172.852112  14900.346458 -0.173486
s_016um_00109_00223-1          0       18  4425.694211  14716.500350 -0.088819
s_016um_00039_00175-1          0       12  5535.624672  13933.920353 -0.173486
s_016um_00037_00193-1          0       10  5571.488924  14221.434174 -0.173486
s_016um_00144_00329-1          0        3  3888.206480  16419.520351 -0.007385

[137051 rows x 5 columns]

In [14]:
common_indices = list(set(adata.obs_names) & set(cell_type.index))
print("Common indices:", len(common_indices))

Common indices: 137051

In [15]:
adata.obs['cell_type'] = cell_type.loc[adata.obs_names, 'cell_type'].values

In [17]:
adata.obs

,tumor_gene_signature,stroma_immune_singnature_genes,t_gene_signature,T_means,leiden,X,Y,cell_type
s_016um_00052_00082-1,-13.163058,-110.718834,-7.980356,-0.173486,10,5307.678916618804,12449.199919631592,0
s_016um_00010_00367-1,-10.281478,-75.933578,-5.291239,-0.115027,0,6040.988190604934,16999.787108627097,1
s_016um_00163_00399-1,8.234170,488.635284,59.490974,1.293282,23,3599.0479211059037,17543.40584821326,0
s_016um_00238_00388-1,-4.404501,-17.279686,-7.980356,-0.173486,21,2396.76805388968,17382.86186754705,0
s_016um_00144_00175-1,4.236984,-45.988926,-4.228531,-0.091925,1,3855.484646416702,13956.137643030437,0
...,...,...,...,...,...,...,...,...
s_016um_00375_00231-1,-3.660754,23.671553,-7.980356,-0.173486,9,172.85211221427807,14900.346458407554,0
s_016um_00109_00223-1,-7.506592,43.515171,-4.085675,-0.088819,18,4425.694210888937,14716.500350242153,0
s_016um_00039_00175-1,-4.674540,-8.500046,-7.980356,-0.173486,12,5535.624672456852,13933.920353056192,0
s_016um_00037_00193-1,-13.163058,-103.328911,-7.980356,-0.173486,10,5571.488924089748,14221.434174253345,0
s_016um_00144_00329-1,-11.279081,80.356499,-0.339695,-0.007385,3,3888.20647986953,16419.520350503226,0

In [22]:
adata.write_h5ad('../test.h5ad')

step3: slecet top 500 highly expressed gene in tumor region

In [23]:
tumor_cells = adata[adata.obs['cell_type'] == 1]
tumor_cells.X.shape

(65742, 18085)

In [24]:
mean_expression = np.mean(tumor_cells.X, axis=0)
top_500_genes = np.argsort(mean_expression)[-500:]

In [25]:
top_500_genes

array([16415,  5011, 18082, 16582, 14607,  7638, 17266, 17667,  3464,
        1899,  7705, 16728, 16611, 18083,  2462,  7541, 14585,  3938,
       13544,  5749,  4523, 16339, 16618, 14668,  8166,  7815,   626,
        4618,  8323, 12777,  9296,  2784,  3384,  7580,  7690,  7575,
       14999, 15506,  8566,  5313, 16631,  2717,  1322,   851,   534,
        2685,  7742,  2205,  7694, 16853, 10209, 16274,  6747, 16981,
       14302,  1937, 17872, 14437, 16590,   878,  8572,  6890,  5842,
        6042,  3332, 14460, 12195,  9764,  3777, 10377, 12279, 10274,
       13601,  6150, 16371, 15874, 17242, 10296, 11099,  4159, 16350,
        3525,  7538,  6619,  8435, 12051, 12715,  3248, 16418, 15112,
       14306,  5669,  9778, 16687, 14052,  8207, 16303,  6638, 11772,
        6018, 17408,  6204, 10361, 10685,  3674,  9298, 11660, 14239,
       12690,  5902, 13557, 17024, 11920,  3941,  7910,  2552, 16537,
       16289,  8204,  3964,  9332,  3691, 12471,  1216,   612,  5349,
       14640, 13582,  7476, 11728,  3773, 15411,  6608,  5315,  3170,
       16349, 14542, 12040, 15647, 11661, 10439,  7569,  8612,  1395,
       14943, 14111, 16271,  9842, 15428,  9370, 16484,  2938, 17113,
       14217, 16527, 16621,  5984,   403,  6190, 13569,  2652, 11638,
        6636, 11289,  6621,  6339,  9941,  6280,  3706,  7852,  2600,
        4821, 16487,  3402,  9926,  9970,  7863,  6480,  6258,   785,
        3648,  6187,  1637,  7610, 16455,  7111, 10056,  4024,  5789,
        8963, 13423, 11227,  6475,  6206,  2315, 15680,  5799,  8607,
       11199, 10326, 17149, 13000, 10548,  1187,  5474, 18078,  1538,
       15519,  7681,  5702, 16547,  5561, 14621,  2297,  3722,  6548,
        3768, 13362,  1243, 10681,  1588,  5901, 14624,  7971,  7878,
        2680,  3805, 10861,  6607, 16565,   724,  2473, 17433,  1922,
       14291, 13134,  8482, 12804,  7654, 16507, 18084,  6429, 10085,
       11918,  7881,  7748,  3611, 16255,  7600, 16672,  9990,  9092,
        2659,  3766, 13090, 16731, 11343, 12918,  4236,  6235, 10455,
        2041, 11995, 14933, 13444, 17168, 17495, 10707,  8308, 17732,
       11586,  4339,  3764, 18081,  2288,  5641,  4338,  5989,  9904,
       10704, 13334, 18077, 14834,  1725, 16320,  3306, 16613,   525,
       10486,  3547,  3317, 10454,  2845, 16614,  5743,  4732, 16683,
       13331,  3868, 10824, 16496, 17498, 14596,  3897,  3455, 12160,
       16867,  7675, 13167,  2739,   609, 15223,  8436,  6650, 18080,
        9779,  4105,  5811,  5529, 10668, 15287, 14536,  7518,   545,
       14389,  3548,  6567, 16373,  4463,  9048, 10790,  1720, 14391,
        2690,  5763,  6326,  3351, 17846,  5558, 15544,  6746, 13589,
        9815, 11122, 11494, 18074,  3878,  6935, 16459,  9918,  6330,
         942, 12422,  1072, 16482, 11500, 14554,  9206,  8291,  1546,
       11516, 12746, 16668,  6291,  2320,  5894,  3154,  5814, 14353,
       17021, 10055,  6501, 18079,  7873, 18075, 10328, 13394, 11352,
        1087,  4343, 14159, 17714,  2792,  6749,  3652,   686, 14656,
       11014,  9317,  7713, 18076,  7627,  2930, 12775, 12270, 14356,
       11689,  5326,  7860, 18041, 10779,  8756, 14655, 10545,  5995,
        5862,  3413,  1192, 10410, 14305, 16134,  6792,  7785,  1721,
       16635,  9626,  5421, 10109,  6566,  5128,  7531,  7530, 14070,
        7846,  9350, 16327,  7822,  3301,  9257, 16399, 14951,  3284,
        1935, 16475, 10246, 13431,  2110,  9879, 15633,  4851, 16852,
       17422,  5589,   901, 10982,   672,   970, 16711, 17728,  2733,
        2785,   693, 11990,  4008,  2732, 14774, 13238, 10667,  5891,
       13748,  7695,  1716, 15550,  9781,  7679,  4342,  7865, 12050,
       16315, 16322,  7758, 15645, 16545, 13446, 10483,   871, 10351,
        2632, 12641, 11098,  3445, 14376,  7794,  9175, 15985, 14584,
        6793, 10900, 10659, 15630, 16400, 12407,  1556, 15729, 11643,
        6193, 10487, 15728,  6973,  2129])

In [26]:
adata = adata[:, top_500_genes]

In [27]:
adata.var_names

Index(['ID1', 'CKMT2', 'MT-ND5', 'DNTTIP1', 'EIF4A3', 'ZFAND1', 'TSPO', 'OGT',
       'SUCLG2', 'ADI1',
       ...
       'PYGB', 'PHGR1', 'ELF3', 'CEACAM6', 'KLF5', 'CD24', 'ST14', 'CEACAM5',
       'MUC12', 'EPCAM'],
      dtype='object', length=500)

In [28]:
adata.X.shape

(137051, 500)

In [29]:
adata.var_names

Index(['ID1', 'CKMT2', 'MT-ND5', 'DNTTIP1', 'EIF4A3', 'ZFAND1', 'TSPO', 'OGT',
       'SUCLG2', 'ADI1',
       ...
       'PYGB', 'PHGR1', 'ELF3', 'CEACAM6', 'KLF5', 'CD24', 'ST14', 'CEACAM5',
       'MUC12', 'EPCAM'],
      dtype='object', length=500)

In [30]:
adata.write_h5ad('../test.h5ad')

In [4]:
data = pd.read_csv('hs38d1.fa_cnvkit.txt', sep='\t',header=None)

In [11]:
human = data[0]

In [14]:
human = human.drop_duplicates()

In [17]:
human.to_csv('human.csv',index=False,header=['Gene'])