In [ ]:
import pandas as pd
import numpy as np
import scanpy as sc
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from scipy.spatial.distance import cdist
import torch.nn.functional as F

In [ ]:
adata = sc.read_h5ad('../example.h5ad')

In [ ]:
adata.obs['X'] = adata.obs['array_row'] *100
adata.obs['Y'] = adata.obs['array_col'] *100
adata.obs

                    in_tissue  array_row  array_col  n_counts     X      Y
AAACAAGTATCTCCCA-1          1         50        102    5625.0  5000  10200
AAACACCAATAACTGC-1          1         59         19    9159.0  5900   1900
AAACAGAGCGACTCCT-1          1         14         94    2660.0  1400   9400
AAACAGGGTCTATATT-1          1         47         13    9020.0  4700   1300
AAACAGTGTTCCTGGG-1          1         73         43    9714.0  7300   4300
...                       ...        ...        ...       ...   ...    ...
TTGTTGTGTGTCAAGA-1          1         31         77    7260.0  3100   7700
TTGTTTCACATCCAGG-1          1         58         42    7510.0  5800   4200
TTGTTTCATTAGTCTA-1          1         60         30    5742.0  6000   3000
TTGTTTCCATACAACT-1          1         45         27   20118.0  4500   2700
TTGTTTGTATTACACG-1          1         73         41    8169.0  7300   4100

[2640 rows x 6 columns]

In [ ]:
adata.obs['tcr'] = np.random.randint(2, size=adata.n_obs)

In [ ]:
adata.obs

,in_tissue,array_row,array_col,n_counts,X,Y,tcr
AAACAAGTATCTCCCA-1,1,50,102,5625.0,5000,10200,1
AAACACCAATAACTGC-1,1,59,19,9159.0,5900,1900,0
AAACAGAGCGACTCCT-1,1,14,94,2660.0,1400,9400,1
AAACAGGGTCTATATT-1,1,47,13,9020.0,4700,1300,1
AAACAGTGTTCCTGGG-1,1,73,43,9714.0,7300,4300,0
...,...,...,...,...,...,...,...
TTGTTGTGTGTCAAGA-1,1,31,77,7260.0,3100,7700,1
TTGTTTCACATCCAGG-1,1,58,42,7510.0,5800,4200,1
TTGTTTCATTAGTCTA-1,1,60,30,5742.0,6000,3000,1
TTGTTTCCATACAACT-1,1,45,27,20118.0,4500,2700,0
TTGTTTGTATTACACG-1,1,73,41,8169.0,7300,4100,0