In [1]:
import pandas as pd
import scanpy as sc

In [2]:
results = sc.read('../predict.h5ad')

In [4]:
results.obs.to_csv('results.csv')

In [2]:
data = pd.read_csv('ig_score_changes.csv')

In [3]:
data

               Gene  IG Score Before Training  IG Score After Training
0          C1orf141                  0.268941                 0.000243
1              PKP1                  0.268941                 0.000022
2              RERE                  0.268941                 0.000227
3             CSMD2                  0.268941                 0.000242
4            HIVEP3                  0.268941                 0.000245
...             ...                       ...                      ...
27195   ANKRD20A12P                  0.268941                 0.268941
27196         MAFIP                  0.268941                 0.268941
27197      MGC70870                  0.268941                 0.268941
27198  LOC102724728                  0.268941                 0.268941
27199  LOC105379550                  0.268941                 0.268941

[27200 rows x 3 columns]

In [5]:
data['change'] = data['IG Score Before Training'] - data['IG Score After Training']

In [6]:
data

,Gene,IG Score Before Training,IG Score After Training,change
0,C1orf141,0.268941,0.000243,0.268699
1,PKP1,0.268941,0.000022,0.268919
2,RERE,0.268941,0.000227,0.268714
3,CSMD2,0.268941,0.000242,0.268700
4,HIVEP3,0.268941,0.000245,0.268696
...,...,...,...,...
27195,ANKRD20A12P,0.268941,0.268941,0.000000
27196,MAFIP,0.268941,0.268941,0.000000
27197,MGC70870,0.268941,0.268941,0.000000
27198,LOC102724728,0.268941,0.268941,0.000000
27199,LOC105379550,0.268941,0.268941,0.000000

In [7]:
#sort by change
data.sort_values('change', ascending=False)

           Gene  IG Score Before Training  IG Score After Training    change
14605       VIM                  0.268941                 0.000005  0.268937
17412      YBX3                  0.268941                 0.000014  0.268928
1840       MCL1                  0.268941                 0.000015  0.268927
23186  LGALS3BP                  0.268941                 0.000015  0.268927
25274     LENG8                  0.268941                 0.000015  0.268927
...         ...                       ...                      ...       ...
25970     WFDC2                  0.268941                 0.954725 -0.685784
24846      APOE                  0.268941                 0.973593 -0.704652
13012    TMSB4X                  0.268941                 0.979171 -0.710229
3724      SFTPB                  0.268941                 0.982532 -0.713591
21961    COL1A1                  0.268941                 0.987710 -0.718769

[27200 rows x 4 columns]

In [9]:
data.to_csv('change.csv',index=False)