In [1]:
import pandas as pd

In [2]:
!pwd

/project/DPDS/Wang_lab/s439765/spatial_tcr/MIL_TCR

In [2]:
ig_score = pd.read_csv('finalize_model/tcell/ig_score_changes_epoch_9.csv')
hla_binder = pd.read_csv('validation/weighted_hla_binders.csv')

In [3]:
ig_score

          Gene  IG Score Before Training  IG Score After Training  Difference
0         BCL2                      -1.0                11.598041   12.598041
1      MAGEA10                      -1.0                11.510351   12.510351
2        OR5V1                      -1.0                11.416059   12.416059
3        OR2H1                      -1.0                11.415375   12.415375
4       MAGEA4                      -1.0                11.314968   12.314968
...        ...                       ...                      ...         ...
23177  ALDH3B2                      -1.0               -14.560724  -13.560724
23178    EPCAM                      -1.0               -14.883138  -13.883138
23179    ERBB2                      -1.0               -14.938863  -13.938863
23180     MUC1                      -1.0               -15.169168  -14.169168
23181    MUCL1                      -1.0               -15.435293  -14.435293

[23182 rows x 4 columns]

In [4]:
hla_binder

,Protein,high_binders,weak_binders,peptides,weight_high_binders,weight_weak_binders,Gene
0,A0A1B0GTB2,35,161,158,1.33434,6.01476,TUNAR
1,A0FGR8,1650,5141,3650,66.33857,206.90966,ESYT2
2,A0MZ66,986,3058,2490,37.17185,122.11799,SHTN1
3,A1A5B4,2017,5786,3094,76.72772,226.48333,ANO9
4,A1L020,746,2298,2046,29.09429,89.34438,MEX3A
...,...,...,...,...,...,...,...
1492,Q9Y6E0,721,2287,1738,28.40909,89.92225,STK24
1493,Q9Y6E2,1058,2759,1642,42.75017,109.90290,BZW2
1494,Q9Y6G1,168,529,362,7.08505,19.98255,TMEM14A
1495,Q9Y6I3,826,2727,2270,31.65657,107.12074,EPN1
1496,Q9Y6M1,1242,3786,2362,47.06136,144.77557,IGF2BP2

In [5]:
stagei_hla_binder = ig_score.merge(hla_binder, on='Gene', how='left')

In [10]:
length = pd.read_csv('validation/pmhc/protein_lengths.csv')

In [11]:
length

     Protein  Length
0     P43358     317
1     P43363     369
2     Q9GZK4     316
3     P10415     239
4     Q9UGF6     321
...      ...     ...
1481  P06731     702
1482  P16422     314
1483  P04626    1255
1484  Q96DR8      90
1485  P15941    1255

[1486 rows x 2 columns]

In [17]:
stagei_hla_binder_length = stagei_hla_binder.merge(length, on='Protein', how='left')

In [18]:
stagei_hla_binder_length.to_csv('validation/stagei_hla_binder.csv', index=False)

In [19]:
stagei_hla_binder_length

,Gene,IG Score Before Training,IG Score After Training,Difference,Protein,high_binders,weak_binders,peptides,weight_high_binders,weight_weak_binders,Length
0,BCL2,-1.0,11.598041,12.598041,P10415,551.0,1691.0,922.0,22.18330,65.98130,239.0
1,MAGEA10,-1.0,11.510351,12.510351,P43363,829.0,2388.0,1442.0,34.15563,99.11258,369.0
2,OR5V1,-1.0,11.416059,12.416059,Q9UGF6,803.0,2325.0,1250.0,32.27697,92.97078,321.0
3,OR2H1,-1.0,11.415375,12.415375,Q9GZK4,874.0,2630.0,1230.0,34.01403,104.48637,316.0
4,MAGEA4,-1.0,11.314968,12.314968,P43358,700.0,2131.0,1234.0,28.55246,82.46990,317.0
...,...,...,...,...,...,...,...,...,...,...,...
23177,ALDH3B2,-1.0,-14.560724,-13.560724,P48448,876.0,2573.0,1506.0,36.80271,101.50563,385.0
23178,EPCAM,-1.0,-14.883138,-13.883138,P16422,505.0,1500.0,1222.0,22.01820,59.09208,314.0
23179,ERBB2,-1.0,-14.938863,-13.938863,P04626,2202.0,6299.0,4986.0,87.87997,253.11845,1255.0
23180,MUC1,-1.0,-15.169168,-14.169168,P15941,3154.0,6429.0,4986.0,120.09936,261.70972,1255.0
23181,MUCL1,-1.0,-15.435293,-14.435293,Q96DR8,113.0,318.0,326.0,4.58602,11.26859,90.0