In [1]:
import pandas as pd

In [14]:
!pwd

/project/DPDS/Wang_lab/s439765/spatial_tcr/MIL_TCR

In [35]:
cell_migration = pd.read_csv('validation/diff_gene/pathaway/cell_migration.csv')

In [36]:
cell_migration

                                             function
0               CCL4 - chemokine (c-c motif) ligand 4
1            S100A8 - s100 calcium binding protein a8
2               CCL5 - chemokine (c-c motif) ligand 5
3             CCR2 - chemokine (c-c motif) receptor 2
4            S100A9 - s100 calcium binding protein a9
..                                                ...
75             ADAM8 - adam metallopeptidase domain 8
76                      SLAMF8 - slam family member 8
77           S100A8 - s100 calcium binding protein a8
78           S100A9 - s100 calcium binding protein a9
79  MDK - midkine (neurite growth-promoting factor 2)

[80 rows x 1 columns]

In [37]:
cell_migration['gene'] = cell_migration['function'].str.split('-').str[0]

In [38]:
cell_migration['function'] = cell_migration['function'].str.split('-').str[1]

In [39]:
cell_migration

                            function     gene
0                       chemokine (c    CCL4
1    s100 calcium binding protein a8  S100A8
2                       chemokine (c    CCL5
3                       chemokine (c    CCR2
4    s100 calcium binding protein a9  S100A9
..                               ...      ...
75    adam metallopeptidase domain 8   ADAM8
76              slam family member 8  SLAMF8
77   s100 calcium binding protein a8  S100A8
78   s100 calcium binding protein a9  S100A9
79           midkine (neurite growth     MDK

[80 rows x 2 columns]

In [40]:
diff_gene = pd.read_csv('validation/diff_gene/all_data_diff_gene_markers_top5000_filtered.csv')
diff_gene

,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5
0,MSLN,-0.996481,3.220000e-26,2.010000e-23,0.082340,0.996481
1,SLC34A2,-0.972979,4.710000e-29,3.410000e-26,0.097124,0.972979
2,CARTPT,-0.903900,1.140000e-24,6.270000e-22,0.107048,0.903900
3,CD24,0.889778,7.230000e-142,1.310000e-137,1.541697,0.889778
4,MX1,0.790000,2.140000e-48,3.230000e-45,0.267711,0.790000
...,...,...,...,...,...,...
4921,CTSA,-0.000085,9.985001e-01,1.000000e+00,0.406757,0.000085
4922,USP10,0.000079,9.992639e-01,1.000000e+00,0.092019,0.000079
4923,CYTH2,-0.000076,9.990819e-01,1.000000e+00,0.163470,0.000076
4924,YIPF5,-0.000035,9.996513e-01,1.000000e+00,0.107927,0.000035
4925,RIN2,-0.000016,9.997787e-01,1.000000e+00,0.213874,0.000016

In [46]:
cell_migration['gene'] = cell_migration['gene'].str.split(' ').str[0]
cell_migration

                            function    gene
0                       chemokine (c    CCL4
1    s100 calcium binding protein a8  S100A8
2                       chemokine (c    CCL5
3                       chemokine (c    CCR2
4    s100 calcium binding protein a9  S100A9
..                               ...     ...
75    adam metallopeptidase domain 8   ADAM8
76              slam family member 8  SLAMF8
77   s100 calcium binding protein a8  S100A8
78   s100 calcium binding protein a9  S100A9
79           midkine (neurite growth     MDK

[80 rows x 2 columns]

In [47]:
cell_migration.drop_duplicates(subset='gene', keep='first', inplace=True)
cell_migration

                                             function    gene
0                                        chemokine (c    CCL4
1                     s100 calcium binding protein a8  S100A8
2                                        chemokine (c    CCL5
3                                        chemokine (c    CCR2
4                     s100 calcium binding protein a9  S100A9
5                            phospholipase c, gamma 1   PLCG1
6                             midkine (neurite growth     MDK
7                                           g protein  GPR183
8                                        chemokine (c   CXCL9
9                                        chemokine (c   CCL18
10                                          ret proto     RET
11                                               zeta   ZAP70
12                  signal recognition particle 54kda   SRP54
13                     adam metallopeptidase domain 8   ADAM8
14                               slam family member 8  SLAMF8
15                             growth factor receptor    GRB7
16           oxidized low density lipoprotein (lectin    OLR1
17   solute carrier family 7 (amino acid transport...  SLC7A5
18                 complement component 5a receptor 1   C5AR1
19                  aminoacyl trna synthetase complex   AIMP1
20                         phosphodiesterase 4b, camp   PDE4B
21                               phosphatidylinositol  PIK3CD
22   chromogranin a (parathyroid secretory protein 1)    CHGA
23                                           platelet   PDGFB
24   integrin, alpha l (antigen cd11a (p180), lymp...   ITGAL
25                                         selectin l    SELL
26      immunoglobulin lambda constant 1 (mcg marker)   IGLC1
27   solute carrier family 7 (amino acid transport...  SLC7A6
28                                   secretogranin ii    SCG2
29   signal transducer and activator of transcript...  STAT5B
45                                       chemokine (c  CXCL10
46                                       chemokine (c    CCL2
47                                      cd99 molecule    CD99
51                                       f11 receptor    F11R
56                                       chemokine (c   CCL19
59                                       chemokine (c  CXCL11
60                                   integrin, beta 7   ITGB7
61                                          myosin ig   MYO1G

In [48]:
cell_migration_log=cell_migration.merge(diff_gene, on='gene', how='left')

In [49]:
cell_migration_log

,function,gene,logfoldchange,pvals,adjusted_pvals,average_count,Unnamed: 5
0,chemokine (c,CCL4,-0.316661,4.703020e-04,1.012549e-02,0.084890,0.316661
1,s100 calcium binding protein a8,S100A8,-0.292955,2.043020e-04,5.203957e-03,0.117188,0.292955
2,chemokine (c,CCL5,-0.295130,9.430000e-12,1.580000e-09,0.502364,0.295130
3,chemokine (c,CCR2,0.577368,8.990000e-10,1.080000e-07,0.073536,0.577368
4,s100 calcium binding protein a9,S100A9,0.288952,4.120000e-13,8.100000e-11,0.665023,0.288952
5,"phospholipase c, gamma 1",PLCG1,-0.515519,1.060000e-09,1.230000e-07,0.099461,0.515519
6,midkine (neurite growth,MDK,-0.284952,2.380000e-06,1.314750e-04,0.202268,0.284952
7,g protein,GPR183,-0.332845,2.310000e-05,9.078030e-04,0.113604,0.332845
8,chemokine (c,CXCL9,-0.443240,7.360000e-27,4.750000e-24,0.604852,0.443240
9,chemokine (c,CCL18,-0.561678,8.560000e-09,8.460000e-07,0.073205,0.561678
10,ret proto,RET,0.336460,6.720000e-05,2.190403e-03,0.101404,0.336460
11,zeta,ZAP70,-0.352628,1.380000e-06,8.310000e-05,0.135530,0.352628
12,signal recognition particle 54kda,SRP54,-0.357366,1.417570e-04,3.950191e-03,0.077188,0.357366
13,adam metallopeptidase domain 8,ADAM8,-0.327649,4.650000e-07,3.160000e-05,0.172060,0.327649
14,slam family member 8,SLAMF8,-0.349173,1.034650e-04,3.103082e-03,0.082684,0.349173
15,growth factor receptor,GRB7,0.561044,2.550000e-21,1.070000e-18,0.226892,0.561044
16,oxidized low density lipoprotein (lectin,OLR1,0.411276,6.270000e-11,9.080000e-09,0.185810,0.411276
17,solute carrier family 7 (amino acid transport...,SLC7A5,-0.285626,1.972372e-03,3.053968e-02,0.077685,0.285626
18,complement component 5a receptor 1,C5AR1,-0.290589,1.039170e-04,3.108644e-03,0.124780,0.290589
19,aminoacyl trna synthetase complex,AIMP1,-0.321492,5.329140e-04,1.112904e-02,0.079511,0.321492
20,"phosphodiesterase 4b, camp",PDE4B,-0.376610,5.070000e-05,1.707683e-03,0.078241,0.376610
21,phosphatidylinositol,PIK3CD,-0.296783,5.150000e-05,1.731062e-03,0.132907,0.296783
22,chromogranin a (parathyroid secretory protein 1),CHGA,-0.728642,7.750000e-14,1.690000e-11,0.082008,0.728642
23,platelet,PDGFB,0.289285,1.893063e-03,2.974461e-02,0.078358,0.289285
24,"integrin, alpha l (antigen cd11a (p180), lymp...",ITGAL,-0.321003,1.550000e-06,9.240000e-05,0.165279,0.321003
25,selectin l,SELL,-0.321515,2.930000e-06,1.574540e-04,0.155365,0.321515
26,immunoglobulin lambda constant 1 (mcg marker),IGLC1,0.523340,2.500000e-34,2.380000e-31,0.790866,0.523340
27,solute carrier family 7 (amino acid transport...,SLC7A6,-0.291493,8.567980e-04,1.590882e-02,0.091971,0.291493
28,secretogranin ii,SCG2,-0.615794,2.370000e-09,2.590000e-07,0.071341,0.615794
29,signal transducer and activator of transcript...,STAT5B,-0.453767,2.150000e-09,2.370000e-07,0.125083,0.453767
30,chemokine (c,CXCL10,0.234161,5.950000e-08,4.990000e-06,0.525538,0.234161
31,chemokine (c,CCL2,-0.203465,3.595016e-03,4.759913e-02,0.147240,0.203465
32,cd99 molecule,CD99,-0.223377,2.370000e-06,1.312510e-04,0.366344,0.223377
33,f11 receptor,F11R,0.203286,5.727730e-04,1.166812e-02,0.218865,0.203286
34,chemokine (c,CCL19,-0.219068,8.722714e-03,8.897365e-02,0.114800,0.219068
35,chemokine (c,CXCL11,0.267081,2.230000e-05,8.800540e-04,0.186475,0.267081
36,"integrin, beta 7",ITGB7,-0.236320,2.848956e-03,4.009600e-02,0.108967,0.236320
37,myosin ig,MYO1G,-0.229936,1.390740e-04,3.900367e-03,0.203543,0.229936

In [50]:
cell_migration_log.to_csv('validation/diff_gene/pathaway/cell_migration_log.csv', index=False)