In [247]:
import scanpy as sc
import pandas as pd
import numpy as np

In [313]:

adata = sc.read_h5ad('/project/DPDS/Wang_lab/shared/spatial_TCR/data/train_validate/Spatial_TCR_Visium/p16/p16.h5ad')
tcr_count = pd.read_csv('/project/DPDS/Wang_lab/shared/spatial_TCR/data/train_validate/Spatial_TCR_Visium/p16/TCR_count_table_p16.csv')

In [314]:
tcr_count

               barcode                  clonotypes  count
0     AAAATGGCACCGGACC    TRBV7-8*00_CASSLVGAGEQFF      2
1     AAACAGCTTTCAGAAG  TRBV7-6*00_CASSPELGGPYEQYF      1
2     AAACAGCTTTCAGAAG  TRBV7-9*00_CASSPELGGPYEQYF      1
3     AAACAGCTTTCGAAGT    TRBV7-8*00_CASSLVGAGEQFF      1
4     AAACCGGGTAGGTACC   TRBV4-1*00_CASSQGLGNTEAFF      5
...                ...                         ...    ...
3089  TTGTTCTAGATACGCT    TRBV7-8*00_CASSLVGAGEQFF      1
3090  TTGTTTCACATCCAGG    TRBV6-5*00_CASIGTGVYEQYF      1
3091  TTGTTTCACATCCAGG    TRBV7-8*00_CASSLVGAGEQFF      1
3092  TTGTTTCCATACAACT    TRBV7-8*00_CASSLVGAGEQFF      1
3093  TTTTAGTGAACGGTGA  TRBV7-9*00_CASSPELGGPYEQYF      1

[3094 rows x 3 columns]

In [315]:
adata.obs

,x1,x2,x3,x4,x5,x_array,y_array,x_pixel,y_pixel
AAACACCAATAACTGC-1,1,59,19,9979,5754,59,19,9979,5754
AAACAGCTTTCAGAAG-1,1,43,9,7819,4982,43,9,7819,4982
AAACAGGGTCTATATT-1,1,47,13,8359,5292,47,13,8359,5292
AAACCGGGTAGGTACC-1,1,42,28,7686,6456,42,28,7686,6456
AAACCGTTCGTCCAGG-1,1,52,42,9038,7540,52,42,9038,7540
...,...,...,...,...,...,...,...,...,...
TTGTGTTTCCCGAAAG-1,1,51,59,8905,8859,51,59,8905,8859
TTGTTAGCAAATTCGA-1,1,22,42,4989,7547,22,42,4989,7547
TTGTTCTAGATACGCT-1,1,21,3,4849,4522,21,3,4849,4522
TTGTTTCATTAGTCTA-1,1,60,30,10116,6607,60,30,10116,6607
TTGTTTCCATACAACT-1,1,45,27,8091,6378,45,27,8091,6378

In [316]:
tcr_count.drop(columns=['clonotypes','count'], inplace=True)
tcr_count

               barcode
0     AAAATGGCACCGGACC
1     AAACAGCTTTCAGAAG
2     AAACAGCTTTCAGAAG
3     AAACAGCTTTCGAAGT
4     AAACCGGGTAGGTACC
...                ...
3089  TTGTTCTAGATACGCT
3090  TTGTTTCACATCCAGG
3091  TTGTTTCACATCCAGG
3092  TTGTTTCCATACAACT
3093  TTTTAGTGAACGGTGA

[3094 rows x 1 columns]

In [317]:
tcr_count.drop_duplicates(inplace=True)

In [318]:
tcr_count

               barcode
0     AAAATGGCACCGGACC
1     AAACAGCTTTCAGAAG
3     AAACAGCTTTCGAAGT
4     AAACCGGGTAGGTACC
5     AAACCGTTCGTCCAGG
...                ...
3086  TTGTTAACTTACATTT
3087  TTGTTCTAGATACGCT
3090  TTGTTTCACATCCAGG
3092  TTGTTTCCATACAACT
3093  TTTTAGTGAACGGTGA

[1458 rows x 1 columns]

In [319]:
tcr_count['T'] = 1

In [320]:
tcr_count.set_index('barcode', inplace=True)

In [321]:
tcr_count

                  T
barcode
AAAATGGCACCGGACC  1
AAACAGCTTTCAGAAG  1
AAACAGCTTTCGAAGT  1
AAACCGGGTAGGTACC  1
AAACCGTTCGTCCAGG  1
...              ..
TTGTTAACTTACATTT  1
TTGTTCTAGATACGCT  1
TTGTTTCACATCCAGG  1
TTGTTTCCATACAACT  1
TTTTAGTGAACGGTGA  1

[1458 rows x 1 columns]

In [322]:
adata.obs.index = adata.obs.index.str.split('-').str[0]

In [323]:
adata.obs

                  x1  x2  x3     x4    x5  x_array  y_array  x_pixel  y_pixel
AAACACCAATAACTGC   1  59  19   9979  5754       59       19     9979     5754
AAACAGCTTTCAGAAG   1  43   9   7819  4982       43        9     7819     4982
AAACAGGGTCTATATT   1  47  13   8359  5292       47       13     8359     5292
AAACCGGGTAGGTACC   1  42  28   7686  6456       42       28     7686     6456
AAACCGTTCGTCCAGG   1  52  42   9038  7540       52       42     9038     7540
...               ..  ..  ..    ...   ...      ...      ...      ...      ...
TTGTGTTTCCCGAAAG   1  51  59   8905  8859       51       59     8905     8859
TTGTTAGCAAATTCGA   1  22  42   4989  7547       22       42     4989     7547
TTGTTCTAGATACGCT   1  21   3   4849  4522       21        3     4849     4522
TTGTTTCATTAGTCTA   1  60  30  10116  6607       60       30    10116     6607
TTGTTTCCATACAACT   1  45  27   8091  6378       45       27     8091     6378

[1716 rows x 9 columns]

In [324]:
overlap_indices = adata.obs_names.intersection(tcr_count.index)
overlap_indices

Index(['AAACAGCTTTCAGAAG', 'AAACCGGGTAGGTACC', 'AAACCGTTCGTCCAGG',
       'AAACCTCATGAAGTTG', 'AAACGAAGATGGAGTA', 'AAACTTAATTGCACGC',
       'AAACTTGCAAACGTAT', 'AAAGAATGACCTTAGA', 'AAAGACTGGGCGCTTT',
       'AAAGTAGCATTGCTCA',
       ...
       'TTGGCTCGCATGAGAC', 'TTGGTCACACTCGTAA', 'TTGGTTGCGGTGCGCG',
       'TTGTACACCTCGAACA', 'TTGTCACCGCGGTATC', 'TTGTGAGGCATGACGC',
       'TTGTGGTAGGAGGGAT', 'TTGTGTTTCCCGAAAG', 'TTGTTCTAGATACGCT',
       'TTGTTTCCATACAACT'],
      dtype='object', length=994)

In [325]:
adata.obs['T'] = 0

In [326]:
adata.obs.loc[overlap_indices, 'T'] = 1

In [327]:
adata.obs[adata.obs['T']== 1]

,x1,x2,x3,x4,x5,x_array,y_array,x_pixel,y_pixel,T
AAACAGCTTTCAGAAG,1,43,9,7819,4982,43,9,7819,4982,1
AAACCGGGTAGGTACC,1,42,28,7686,6456,42,28,7686,6456,1
AAACCGTTCGTCCAGG,1,52,42,9038,7540,52,42,9038,7540,1
AAACCTCATGAAGTTG,1,37,19,7010,5759,37,19,7010,5759,1
AAACGAAGATGGAGTA,1,58,4,9842,4591,58,4,9842,4591,1
...,...,...,...,...,...,...,...,...,...,...
TTGTGAGGCATGACGC,1,43,13,7819,5293,43,13,7819,5293,1
TTGTGGTAGGAGGGAT,1,50,28,8766,6455,50,28,8766,6455,1
TTGTGTTTCCCGAAAG,1,51,59,8905,8859,51,59,8905,8859,1
TTGTTCTAGATACGCT,1,21,3,4849,4522,21,3,4849,4522,1
TTGTTTCCATACAACT,1,45,27,8091,6378,45,27,8091,6378,1

In [328]:
adata.obs['X'] = adata.obs['x_array'] *100
adata.obs['Y'] = adata.obs['y_array'] *100
adata.obs

,x1,x2,x3,x4,x5,x_array,y_array,x_pixel,y_pixel,T,X,Y
AAACACCAATAACTGC,1,59,19,9979,5754,59,19,9979,5754,0,5900,1900
AAACAGCTTTCAGAAG,1,43,9,7819,4982,43,9,7819,4982,1,4300,900
AAACAGGGTCTATATT,1,47,13,8359,5292,47,13,8359,5292,0,4700,1300
AAACCGGGTAGGTACC,1,42,28,7686,6456,42,28,7686,6456,1,4200,2800
AAACCGTTCGTCCAGG,1,52,42,9038,7540,52,42,9038,7540,1,5200,4200
...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTGTTTCCCGAAAG,1,51,59,8905,8859,51,59,8905,8859,1,5100,5900
TTGTTAGCAAATTCGA,1,22,42,4989,7547,22,42,4989,7547,0,2200,4200
TTGTTCTAGATACGCT,1,21,3,4849,4522,21,3,4849,4522,1,2100,300
TTGTTTCATTAGTCTA,1,60,30,10116,6607,60,30,10116,6607,0,6000,3000
TTGTTTCCATACAACT,1,45,27,8091,6378,45,27,8091,6378,1,4500,2700

In [329]:
adata.obs['cell_type'] = adata.obs['T']+1

In [330]:
adata.obs

,x1,x2,x3,x4,x5,x_array,y_array,x_pixel,y_pixel,T,X,Y,cell_type
AAACACCAATAACTGC,1,59,19,9979,5754,59,19,9979,5754,0,5900,1900,1
AAACAGCTTTCAGAAG,1,43,9,7819,4982,43,9,7819,4982,1,4300,900,2
AAACAGGGTCTATATT,1,47,13,8359,5292,47,13,8359,5292,0,4700,1300,1
AAACCGGGTAGGTACC,1,42,28,7686,6456,42,28,7686,6456,1,4200,2800,2
AAACCGTTCGTCCAGG,1,52,42,9038,7540,52,42,9038,7540,1,5200,4200,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTGTTTCCCGAAAG,1,51,59,8905,8859,51,59,8905,8859,1,5100,5900,2
TTGTTAGCAAATTCGA,1,22,42,4989,7547,22,42,4989,7547,0,2200,4200,1
TTGTTCTAGATACGCT,1,21,3,4849,4522,21,3,4849,4522,1,2100,300,2
TTGTTTCATTAGTCTA,1,60,30,10116,6607,60,30,10116,6607,0,6000,3000,1
TTGTTTCCATACAACT,1,45,27,8091,6378,45,27,8091,6378,1,4500,2700,2

In [332]:
adata.write_h5ad('/project/DPDS/Wang_lab/shared/spatial_TCR/data/train_validate/Spatial_TCR_Visium/p16/p16.h5ad')

In [333]:
!pwd

/project/DPDS/Wang_lab/s439765/spatial_tcr/MIL_TCR/scripts