In [1]:
import pandas as pd

In [2]:
!pwd

/project/DPDS/Wang_lab/s439765/spatial_tcr/MIL_TCR

In [11]:
ig_score = pd.read_csv('finalize_model/tcell/ig_score_changes_epoch_10.csv')
hla_binder = pd.read_csv('validation/weighted_hla_binder.csv')

In [12]:
ig_score

          Gene  IG Score Before Training  IG Score After Training  Difference
0       MAGEA4                      -1.0                11.327682   12.327682
1      MAGEA10                      -1.0                11.313536   12.313536
2        OR2H1                      -1.0                11.296708   12.296708
3         BCL2                      -1.0                11.267946   12.267946
4        OR5V1                      -1.0                11.235064   12.235064
...        ...                       ...                      ...         ...
23177  CEACAM5                      -1.0               -14.699956  -13.699956
23178    EPCAM                      -1.0               -14.769582  -13.769582
23179    ERBB2                      -1.0               -14.839805  -13.839805
23180    MUCL1                      -1.0               -15.100492  -14.100492
23181     MUC1                      -1.0               -15.267399  -14.267399

[23182 rows x 4 columns]

In [17]:
ig_score[ig_score['Difference']!=1]['Gene'].to_csv('need_netMHCpan.csv',index=False)

In [22]:
hla_binder

,Protein,high_binders,weak_binders,peptides,weight_high_binders,weight_weak_binders,Gene
0,A0A075B759,220,680,622,8.69280,26.07444,PPIAL4E
1,A0A096LP55,88,327,330,3.07994,13.45168,UQCRHL
2,A0A0A6YYL3,694,2341,2142,26.99475,94.04584,POTEB
3,A0A0B4J2A2,216,696,622,8.61314,26.95222,PPIAL4C
4,A0A0D9SF12,347,1052,546,14.01951,42.04978,CCDC163P
...,...,...,...,...,...,...,...
7644,Q9Y6W6,953,2676,1894,39.24637,109.54181,DUSP10
7645,Q9Y6W8,429,1264,762,19.65368,51.80155,ICOS
7646,Q9Y6X2,1497,4150,2478,60.95286,169.62487,PIAS3
7647,Q9Y6X9,2191,5946,4094,86.12944,225.20434,MORC2
7648,Q9Y6Y9,341,1022,606,13.92788,41.07816,LY96

In [23]:
stagei_hla_binder = ig_score.merge(hla_binder, on='Gene', how='left')

In [24]:
stagei_hla_binder.to_csv('validation/stagei_hla_binder.csv', index=False)

In [25]:
stagei_hla_binder

,Gene,IG Score Before Training,IG Score After Training,Difference,Protein,high_binders,weak_binders,peptides,weight_high_binders,weight_weak_binders
0,BCL2,-1.0,11.598041,12.598041,NaN,NaN,NaN,NaN,NaN,NaN
1,MAGEA10,-1.0,11.510351,12.510351,P43363,829.0,2388.0,1442.0,34.15563,99.11258
2,OR5V1,-1.0,11.416059,12.416059,Q9UGF6,803.0,2325.0,1250.0,32.27697,92.97078
3,OR2H1,-1.0,11.415375,12.415375,Q9GZK4,874.0,2630.0,1230.0,34.01403,104.48637
4,MAGEA4,-1.0,11.314968,12.314968,P43358,700.0,2131.0,1234.0,28.55246,82.46990
...,...,...,...,...,...,...,...,...,...,...
23326,ALDH3B2,-1.0,-14.560724,-13.560724,P48448,876.0,2573.0,1506.0,36.80271,101.50563
23327,EPCAM,-1.0,-14.883138,-13.883138,NaN,NaN,NaN,NaN,NaN,NaN
23328,ERBB2,-1.0,-14.938863,-13.938863,NaN,NaN,NaN,NaN,NaN,NaN
23329,MUC1,-1.0,-15.169168,-14.169168,P15941,3154.0,6429.0,4986.0,120.09936,261.70972
23330,MUCL1,-1.0,-15.435293,-14.435293,Q96DR8,113.0,318.0,326.0,4.58602,11.26859

In [43]:
null_data = stagei_hla_binder[stagei_hla_binder.isnull().any(axis=1)]

In [44]:
null_data = null_data[null_data['Difference'].astype(float)!=1]

In [47]:
null_data = null_data['Gene']

In [48]:
null_data.to_csv('validation/null_data.csv', index=False)