In [1]:
import pandas as pd

In [8]:
genomewide_results = pd.read_csv('validation/cripser/T_cell_exhaustion/genomewide_results.csv')

In [ ]:
# Adjust the thresholds to be less strict for a broader selection
fdr_threshold = 0.1  # Allow slightly higher FDR
lfc_threshold = 0.3  # Lower the threshold for Log Fold Change
z_score_threshold = 2  # Include genes with slightly lower Z-scores

# Reapply the filtering with the relaxed thresholds
relaxed_filtered_genes = genomewide_results[
    (
        (genomewide_results['B16_tumor_merge_fdr'] < fdr_threshold) &
        (genomewide_results['B16_tumor_merge_lfc_diff'].abs() > lfc_threshold) &
        (genomewide_results['B16_tumor_merge_z'].abs() > z_score_threshold)
    ) |
    (
        (genomewide_results['MC38_T_v_I_merge_fdr'] < fdr_threshold) &
        (genomewide_results['MC38_T_v_I_merge_lfc_diff'].abs() > lfc_threshold) &
        (genomewide_results['MC38_T_v_I_merge_z'].abs() > z_score_threshold)
    )
]


# Display the first few rows of the relaxed filtering results
relaxed_filtered_genes

,Gene,B16_tumor_merge_z,B16_tumor_merge_fdr,B16_tumor_merge_lfc_diff,B16_spl_merge_z,B16_spl_merge_fdr,B16_spl_merge_lfc_diff,MC38_S_v_I_merge_z,MC38_S_v_I_merge_fdr,MC38_S_v_I_merge_lfc_diff,...,MC38_T_v_I_merge_lfc_diff,invitro_c_v_i_merge_z,invitro_c_v_i_merge_fdr,invitro_c_v_i_merge_lfc_diff,invitro_a_v_i_merge_z,invitro_a_v_i_merge_fdr,invitro_a_v_i_merge_lfc_diff,invitro_c_v_a_merge_z,invitro_c_v_a_merge_fdr,invitro_c_v_a_merge_lfc_diff
2,3830406C13RIK,-0.568926,1.000000e+00,-0.216544,-1.722738,1.000000e+00,-0.558857,-3.527895,9.173444e-02,-1.077429,...,-1.552595,0.935960,1.000000e+00,0.179957,0.709872,1.000000e+00,0.074690,0.606929,1.000000e+00,0.105267
3,9130204L05RIK,-4.569648,1.065025e-03,-2.066490,-3.156624,3.192136e-01,-1.018939,-3.819542,3.034980e-02,-1.216280,...,-1.659517,0.567524,1.000000e+00,0.064006,4.597153,1.062192e-03,0.384695,-2.286776,1.000000e+00,-0.320689
7,ACO2,-11.565953,1.800000e-28,-5.518797,-15.869188,3.070000e-54,-4.858817,-10.271075,2.820000e-22,-3.203754,...,-3.702261,-4.897155,2.460020e-04,-0.726837,-8.174438,8.260000e-14,-0.716546,-0.235827,1.000000e+00,-0.010291
9,ACTB,-10.906511,3.100000e-25,-5.082696,-18.234965,8.170000e-72,-5.641695,-12.860118,2.260000e-35,-4.001852,...,-4.431912,-9.351645,2.450000e-18,-1.452664,-18.360722,8.100000e-73,-1.642133,1.176008,1.000000e+00,0.189469
11,ACTR8,-5.580149,5.580000e-06,-2.595098,-8.674516,1.120000e-15,-2.615987,-6.201292,1.480000e-07,-1.894352,...,-2.290468,-1.738477,1.000000e+00,-0.271940,-12.024223,7.710000e-31,-1.059789,5.570393,6.460000e-06,0.787849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,WDR25,-6.859041,1.730000e-09,-3.424346,-5.993530,4.870000e-07,-1.834474,-3.810228,3.137760e-02,-1.196241,...,-1.857673,-2.680670,1.000000e+00,-0.373229,-1.608058,1.000000e+00,-0.148213,-1.927825,1.000000e+00,-0.225017
289,WDR33,-5.804288,1.530000e-06,-2.751679,-3.942874,1.739036e-02,-1.317406,-8.839794,2.760000e-16,-2.716498,...,-2.755405,2.299569,1.000000e+00,0.357760,-5.869678,1.140000e-06,-0.520236,6.129906,2.280000e-07,0.877995
290,WDR82,-13.632659,7.680000e-40,-6.310832,-14.445497,7.890000e-45,-4.457126,-9.678487,1.090000e-19,-3.056644,...,-2.873321,5.438123,1.400000e-05,0.878680,-18.957454,1.150000e-77,-1.690365,17.614380,5.560000e-67,2.569045
292,YME1L1,-3.606652,5.924298e-02,-1.457329,-0.425349,1.000000e+00,-0.126996,-3.508405,9.827484e-02,-1.117347,...,-2.057941,1.343493,1.000000e+00,0.184822,-5.597828,5.640000e-06,-0.509054,4.890891,2.509510e-04,0.693876
293,ZAP70,-5.622698,4.380000e-06,-2.430853,-6.742112,3.840000e-09,-2.065508,-5.529092,8.270000e-06,-1.741270,...,-2.528485,18.670043,2.560000e-75,2.890842,1.129669,1.000000e+00,0.091033,19.546962,1.280000e-82,2.799809

In [13]:
relaxed_filtered_genes.to_csv('validation/cripser/T_cell_exhaustion/relaxed_filtered_genes.csv', index=False)

In [35]:
strict_filtered_genes = genomewide_results[
    (
        # Significant in B16 melanoma model
        (genomewide_results['B16_tumor_merge_fdr'] < 0.05) &
        (genomewide_results['B16_tumor_merge_lfc_diff'].abs() > 0.5) &
        (genomewide_results['B16_tumor_merge_z'].abs() > 3)
    ) &
    (
        # Significant in MC38 colorectal cancer model
        (genomewide_results['MC38_T_v_I_merge_fdr'] < 0.05) &
        (genomewide_results['MC38_T_v_I_merge_lfc_diff'].abs() > 0.5) &
        (genomewide_results['MC38_T_v_I_merge_z'].abs() > 3)
    ) &
    (
        # Significant in in vitro experiments
        (genomewide_results['invitro_c_v_i_merge_fdr'] < 0.05) &
        (genomewide_results['invitro_c_v_i_merge_lfc_diff'].abs() > 0.5) &
        (genomewide_results['invitro_c_v_i_merge_z'].abs() > 3)
    )
]


# Display the filtered genes
strict_filtered_genes

,Gene,B16_tumor_merge_z,B16_tumor_merge_fdr,B16_tumor_merge_lfc_diff,B16_spl_merge_z,B16_spl_merge_fdr,B16_spl_merge_lfc_diff,MC38_S_v_I_merge_z,MC38_S_v_I_merge_fdr,MC38_S_v_I_merge_lfc_diff,...,MC38_T_v_I_merge_lfc_diff,invitro_c_v_i_merge_z,invitro_c_v_i_merge_fdr,invitro_c_v_i_merge_lfc_diff,invitro_a_v_i_merge_z,invitro_a_v_i_merge_fdr,invitro_a_v_i_merge_lfc_diff,invitro_c_v_a_merge_z,invitro_c_v_a_merge_fdr,invitro_c_v_a_merge_lfc_diff
7,ACO2,-11.565953,1.800000e-28,-5.518797,-15.869188,3.070000e-54,-4.858817,-10.271075,2.820000e-22,-3.203754,...,-3.702261,-4.897155,2.460020e-04,-0.726837,-8.174438,8.260000e-14,-0.716546,-0.235827,1.000000e+00,-0.010291
9,ACTB,-10.906511,3.100000e-25,-5.082696,-18.234965,8.170000e-72,-5.641695,-12.860118,2.260000e-35,-4.001852,...,-4.431912,-9.351645,2.450000e-18,-1.452664,-18.360722,8.100000e-73,-1.642133,1.176008,1.000000e+00,0.189469
41,CASP8,-5.891914,9.050000e-07,-2.575602,-8.750308,5.740000e-16,-2.724633,-7.089474,3.650000e-10,-2.167198,...,-3.062920,11.652589,6.390000e-29,1.827864,-6.154461,1.990000e-07,-0.557607,16.430587,3.340000e-58,2.385472
44,CD3D,-9.149887,1.590000e-17,-3.908387,-11.325418,2.810000e-27,-3.483121,-7.770253,2.170000e-12,-2.431471,...,-2.746026,21.240315,1.200000e-97,3.352914,-0.372207,1.000000e+00,-0.032566,23.292421,1.570000e-117,3.385480
55,COPA,-7.875134,9.090000e-13,-3.497903,-9.730608,6.180000e-20,-3.010837,-9.561838,3.370000e-19,-2.932982,...,-3.547153,-6.940357,1.070000e-09,-1.055599,-8.590919,2.430000e-15,-0.752979,-2.195339,1.000000e+00,-0.302620
69,CYC1,-11.138022,2.380000e-26,-4.875482,-9.758443,4.720000e-20,-2.977775,-9.334304,2.950000e-18,-2.897934,...,-2.894656,-6.613200,1.000000e-08,-1.031894,-9.315164,3.470000e-18,-0.829736,-1.423839,1.000000e+00,-0.202157
80,DPY30,-5.365254,1.860000e-05,-2.328415,-7.929442,5.770000e-13,-2.345018,-4.297020,4.137322e-03,-1.361015,...,-2.622489,4.490376,1.770333e-03,0.666019,-1.501530,1.000000e+00,-0.133824,5.801714,1.690000e-06,0.799843
85,EIF2S3X,-9.543903,3.890000e-19,-4.725818,-13.824110,5.360000e-41,-4.196380,-5.887717,1.010000e-06,-1.817312,...,-2.220161,-6.111158,2.620000e-07,-0.878474,-7.821829,1.440000e-12,-0.667302,-1.726328,1.000000e+00,-0.211172
91,FERMT3,-9.597921,2.320000e-19,-4.650928,-3.625451,6.028773e-02,-1.093978,-5.111928,7.970000e-05,-1.529479,...,-2.478185,24.962912,4.620000e-135,3.823055,1.723447,1.000000e+00,0.145688,26.015046,1.000000e-146,3.677368
100,GANAB,-9.142367,1.700000e-17,-4.184495,-10.982076,1.320000e-25,-3.325972,-6.389883,4.450000e-08,-2.000833,...,-2.536397,5.011522,1.377030e-04,0.780311,-2.091327,1.000000e+00,-0.194197,6.713362,5.020000e-09,0.974508
105,GLRX5,-11.209393,1.070000e-26,-5.263455,-13.526562,3.190000e-39,-4.198721,-11.847335,6.640000e-30,-3.687009,...,-3.897217,4.256285,5.050790e-03,0.663263,-3.039962,5.229034e-01,-0.279633,6.477285,2.450000e-08,0.942897
118,H13,-6.296080,7.420000e-08,-3.289233,-8.119144,1.240000e-13,-2.453634,-5.938979,7.540000e-07,-1.902159,...,-1.899104,3.773149,3.868793e-02,0.578540,0.455071,1.000000e+00,0.067611,3.882234,2.463332e-02,0.510929
125,HUWE1,-7.559329,1.060000e-11,-3.481683,-8.389735,1.310000e-14,-2.565136,-5.933213,7.770000e-07,-1.810588,...,-2.257734,-4.355332,3.268483e-03,-0.619058,-10.857785,5.270000e-25,-0.956409,2.008998,1.000000e+00,0.337351
127,INO80,-7.305671,7.120000e-11,-3.255381,-7.869680,9.280000e-13,-2.339000,-4.947629,1.863040e-04,-1.526638,...,-1.675732,-4.295017,4.279649e-03,-0.714003,-15.264341,3.940000e-50,-1.360102,4.766645,4.664230e-04,0.646098
143,KIN,-9.093023,2.670000e-17,-4.515991,-8.250076,4.230000e-14,-2.518911,-7.799819,1.720000e-12,-2.319439,...,-2.656826,-5.537484,8.010000e-06,-0.827098,-5.847335,1.300000e-06,-0.513566,-2.379651,1.000000e+00,-0.313532
148,LCK,-7.672033,4.470000e-12,-3.915347,-6.296503,7.340000e-08,-1.965662,-8.542681,3.710000e-15,-2.618488,...,-1.671064,6.689808,5.990000e-09,1.066358,-1.207011,1.000000e+00,-0.108535,8.006799,3.250000e-13,1.174893
149,LCP2,-6.286833,7.840000e-08,-3.375274,-4.385471,2.557741e-03,-1.357125,-5.269945,3.450000e-05,-1.589328,...,-2.706528,15.630402,1.320000e-52,2.473870,-0.432619,1.000000e+00,-0.042450,17.227956,4.750000e-64,2.516320
176,NACA,-9.230153,7.570000e-18,-4.096802,-9.304765,3.680000e-18,-2.846528,-9.607148,2.190000e-19,-2.949724,...,-3.872428,-7.331143,6.320000e-11,-1.142274,-14.523554,2.540000e-45,-1.284773,1.037168,1.000000e+00,0.142499
182,NUP133,-9.014660,5.430000e-17,-4.382287,-9.644586,1.430000e-19,-2.990931,-7.446680,2.620000e-11,-2.254965,...,-3.348100,-4.875245,2.716840e-04,-0.679410,-14.917308,7.550000e-48,-1.298365,4.002352,1.498911e-02,0.618956
185,OXA1L,-9.622054,1.850000e-19,-4.206954,-11.237469,7.610000e-27,-3.385199,-8.608492,2.100000e-15,-2.734015,...,-2.247497,-5.272752,3.480000e-05,-0.802510,-12.906340,1.210000e-35,-1.135146,2.286980,1.000000e+00,0.332636
189,PDIA3,-7.491711,1.770000e-11,-3.645992,-5.146090,6.090000e-05,-1.582787,-2.719875,1.000000e+00,-0.830294,...,-1.273703,8.153949,9.790000e-14,1.280142,1.023067,1.000000e+00,0.081032,8.195426,6.940000e-14,1.199110
193,PGK1,-9.621759,1.850000e-19,-4.654905,-18.024346,3.750000e-70,-5.474464,-9.597638,2.390000e-19,-2.926471,...,-3.995585,-5.035717,1.218720e-04,-0.769605,-7.720833,3.170000e-12,-0.687291,-0.694846,1.000000e+00,-0.082314
224,SEC61B,-5.976471,5.450000e-07,-2.577794,-8.232441,4.880000e-14,-2.498145,-6.611138,1.030000e-08,-2.076393,...,-2.503069,14.192209,2.970000e-43,2.192562,-8.179731,7.940000e-14,-0.725907,20.468410,1.210000e-90,2.918468
225,SEC62,-6.680146,5.870000e-09,-3.206053,-6.196560,1.390000e-07,-1.924676,-4.374274,2.924095e-03,-1.327992,...,-2.535861,18.612116,7.540000e-75,2.888132,-3.357404,1.825328e-01,-0.303671,22.269206,2.170000e-107,3.191804
226,SEC63,-11.292599,4.170000e-27,-5.301353,-9.645609,1.420000e-19,-2.929702,-7.608296,7.670000e-12,-2.359586,...,-2.335292,16.842871,3.470000e-61,2.582936,-6.674723,6.610000e-09,-0.600432,22.394219,1.330000e-108,3.183368
240,SMARCB1,-5.472188,1.030000e-05,-2.574365,-7.752880,2.320000e-12,-2.417306,-5.933577,7.770000e-07,-1.827100,...,-2.160577,-4.883096,2.621270e-04,-0.727450,-5.237971,4.160000e-05,-0.451148,-2.025563,1.000000e+00,-0.276302
245,SPCS2,-7.575692,9.360000e-12,-3.634336,-7.984412,3.710000e-13,-2.458132,-6.008744,4.940000e-07,-1.858269,...,-2.825730,8.474030,6.660000e-15,1.255710,-4.796332,4.039940e-04,-0.429594,12.155945,1.520000e-31,1.685304
246,SPCS3,-8.733067,6.770000e-16,-4.480554,-6.964241,8.250000e-10,-2.166944,-5.908970,8.950000e-07,-1.800159,...,-1.640638,12.560837,9.980000e-34,1.898572,-8.090899,1.640000e-13,-0.732581,18.605042,8.540000e-75,2.631153
247,SPTSSA,-12.394666,8.300000e-33,-5.902274,-10.981855,1.320000e-25,-3.347373,-11.095546,3.930000e-26,-3.428758,...,-5.119947,-7.142348,2.530000e-10,-1.086156,-9.308602,3.680000e-18,-0.818911,-1.976134,1.000000e+00,-0.267244
252,SYVN1,-4.778501,3.938330e-04,-2.381352,-4.074815,1.008515e-02,-1.236120,-5.320935,2.620000e-05,-1.658671,...,-2.324786,3.954431,1.848883e-02,0.625388,-4.193312,6.652845e-03,-0.374444,6.882185,1.570000e-09,0.999831
262,TLN1,-6.275900,8.380000e-08,-3.409051,-1.633664,1.000000e+00,-0.482074,-1.197631,1.000000e+00,-0.300960,...,-2.286619,23.957375,2.310000e-124,3.670848,1.868013,1.000000e+00,0.163297,24.845935,8.530000e-134,3.507551
274,TPI1,-12.138029,1.970000e-31,-5.665860,-16.928738,8.230000e-62,-5.153467,-10.778276,1.290000e-24,-3.315729,...,-3.371907,-6.777617,3.310000e-09,-1.003955,-4.801984,3.943240e-04,-0.432495,-4.401435,2.623911e-03,-0.571461
280,UBE2CBP,-5.742469,2.190000e-06,-2.654110,-6.772930,3.120000e-09,-2.042247,-4.112672,9.269222e-03,-1.295066,...,-1.264228,5.204713,5.010000e-05,0.803657,0.592866,1.000000e+00,0.052733,5.283828,3.180000e-05,0.750925
290,WDR82,-13.632659,7.680000e-40,-6.310832,-14.445497,7.890000e-45,-4.457126,-9.678487,1.090000e-19,-3.056644,...,-2.873321,5.438123,1.400000e-05,0.878680,-18.957454,1.150000e-77,-1.690365,17.614380,5.560000e-67,2.569045
293,ZAP70,-5.622698,4.380000e-06,-2.430853,-6.742112,3.840000e-09,-2.065508,-5.529092,8.270000e-06,-1.741270,...,-2.528485,18.670043,2.560000e-75,2.890842,1.129669,1.000000e+00,0.091033,19.546962,1.280000e-82,2.799809

In [36]:
strict_filtered_genes.to_csv('validation/cripser/T_cell_exhaustion/strict_filtered_genes.csv', index=False)

In [37]:
diffex_genes = pd.read_csv('validation/diff_gene/all_data_diff_gene_markers_top5000_filtered.csv')

In [39]:
strict_filtered_genes = strict_filtered_genes.merge(diffex_genes[['gene', 'logfoldchange']], left_on='Gene',
                                                    right_on='gene',
                                                    how='left')

In [41]:
strict_filtered_genes.dropna(subset=['logfoldchange'], inplace=True)

In [42]:
strict_filtered_genes

,Gene,B16_tumor_merge_z,B16_tumor_merge_fdr,B16_tumor_merge_lfc_diff,B16_spl_merge_z,B16_spl_merge_fdr,B16_spl_merge_lfc_diff,MC38_S_v_I_merge_z,MC38_S_v_I_merge_fdr,MC38_S_v_I_merge_lfc_diff,...,invitro_c_v_i_merge_fdr,invitro_c_v_i_merge_lfc_diff,invitro_a_v_i_merge_z,invitro_a_v_i_merge_fdr,invitro_a_v_i_merge_lfc_diff,invitro_c_v_a_merge_z,invitro_c_v_a_merge_fdr,invitro_c_v_a_merge_lfc_diff,gene,logfoldchange
0,ACO2,-11.565953,1.800000e-28,-5.518797,-15.869188,3.070000e-54,-4.858817,-10.271075,2.820000e-22,-3.203754,...,2.460020e-04,-0.726837,-8.174438,8.260000e-14,-0.716546,-0.235827,1.000000e+00,-0.010291,ACO2,-0.157900
2,CASP8,-5.891914,9.050000e-07,-2.575602,-8.750308,5.740000e-16,-2.724633,-7.089474,3.650000e-10,-2.167198,...,6.390000e-29,1.827864,-6.154461,1.990000e-07,-0.557607,16.430587,3.340000e-58,2.385472,CASP8,0.102020
3,CD3D,-9.149887,1.590000e-17,-3.908387,-11.325418,2.810000e-27,-3.483121,-7.770253,2.170000e-12,-2.431471,...,1.200000e-97,3.352914,-0.372207,1.000000e+00,-0.032566,23.292421,1.570000e-117,3.385480,CD3D,-0.407979
4,COPA,-7.875134,9.090000e-13,-3.497903,-9.730608,6.180000e-20,-3.010837,-9.561838,3.370000e-19,-2.932982,...,1.070000e-09,-1.055599,-8.590919,2.430000e-15,-0.752979,-2.195339,1.000000e+00,-0.302620,COPA,-0.048960
5,CYC1,-11.138022,2.380000e-26,-4.875482,-9.758443,4.720000e-20,-2.977775,-9.334304,2.950000e-18,-2.897934,...,1.000000e-08,-1.031894,-9.315164,3.470000e-18,-0.829736,-1.423839,1.000000e+00,-0.202157,CYC1,-0.134573
6,DPY30,-5.365254,1.860000e-05,-2.328415,-7.929442,5.770000e-13,-2.345018,-4.297020,4.137322e-03,-1.361015,...,1.770333e-03,0.666019,-1.501530,1.000000e+00,-0.133824,5.801714,1.690000e-06,0.799843,DPY30,-0.053760
8,FERMT3,-9.597921,2.320000e-19,-4.650928,-3.625451,6.028773e-02,-1.093978,-5.111928,7.970000e-05,-1.529479,...,4.620000e-135,3.823055,1.723447,1.000000e+00,0.145688,26.015046,1.000000e-146,3.677368,FERMT3,-0.248716
9,GANAB,-9.142367,1.700000e-17,-4.184495,-10.982076,1.320000e-25,-3.325972,-6.389883,4.450000e-08,-2.000833,...,1.377030e-04,0.780311,-2.091327,1.000000e+00,-0.194197,6.713362,5.020000e-09,0.974508,GANAB,0.057551
10,GLRX5,-11.209393,1.070000e-26,-5.263455,-13.526562,3.190000e-39,-4.198721,-11.847335,6.640000e-30,-3.687009,...,5.050790e-03,0.663263,-3.039962,5.229034e-01,-0.279633,6.477285,2.450000e-08,0.942897,GLRX5,-0.130769
15,LCK,-7.672033,4.470000e-12,-3.915347,-6.296503,7.340000e-08,-1.965662,-8.542681,3.710000e-15,-2.618488,...,5.990000e-09,1.066358,-1.207011,1.000000e+00,-0.108535,8.006799,3.250000e-13,1.174893,LCK,-0.188598
16,LCP2,-6.286833,7.840000e-08,-3.375274,-4.385471,2.557741e-03,-1.357125,-5.269945,3.450000e-05,-1.589328,...,1.320000e-52,2.473870,-0.432619,1.000000e+00,-0.042450,17.227956,4.750000e-64,2.516320,LCP2,-0.080754
18,NUP133,-9.014660,5.430000e-17,-4.382287,-9.644586,1.430000e-19,-2.990931,-7.446680,2.620000e-11,-2.254965,...,2.716840e-04,-0.679410,-14.917308,7.550000e-48,-1.298365,4.002352,1.498911e-02,0.618956,NUP133,-0.128980
19,OXA1L,-9.622054,1.850000e-19,-4.206954,-11.237469,7.610000e-27,-3.385199,-8.608492,2.100000e-15,-2.734015,...,3.480000e-05,-0.802510,-12.906340,1.210000e-35,-1.135146,2.286980,1.000000e+00,0.332636,OXA1L,-0.104097
20,PDIA3,-7.491711,1.770000e-11,-3.645992,-5.146090,6.090000e-05,-1.582787,-2.719875,1.000000e+00,-0.830294,...,9.790000e-14,1.280142,1.023067,1.000000e+00,0.081032,8.195426,6.940000e-14,1.199110,PDIA3,0.003540
22,SEC61B,-5.976471,5.450000e-07,-2.577794,-8.232441,4.880000e-14,-2.498145,-6.611138,1.030000e-08,-2.076393,...,2.970000e-43,2.192562,-8.179731,7.940000e-14,-0.725907,20.468410,1.210000e-90,2.918468,SEC61B,0.041262
23,SEC62,-6.680146,5.870000e-09,-3.206053,-6.196560,1.390000e-07,-1.924676,-4.374274,2.924095e-03,-1.327992,...,7.540000e-75,2.888132,-3.357404,1.825328e-01,-0.303671,22.269206,2.170000e-107,3.191804,SEC62,0.042821
24,SEC63,-11.292599,4.170000e-27,-5.301353,-9.645609,1.420000e-19,-2.929702,-7.608296,7.670000e-12,-2.359586,...,3.470000e-61,2.582936,-6.674723,6.610000e-09,-0.600432,22.394219,1.330000e-108,3.183368,SEC63,-0.038515
25,SMARCB1,-5.472188,1.030000e-05,-2.574365,-7.752880,2.320000e-12,-2.417306,-5.933577,7.770000e-07,-1.827100,...,2.621270e-04,-0.727450,-5.237971,4.160000e-05,-0.451148,-2.025563,1.000000e+00,-0.276302,SMARCB1,0.035315
27,SPCS3,-8.733067,6.770000e-16,-4.480554,-6.964241,8.250000e-10,-2.166944,-5.908970,8.950000e-07,-1.800159,...,9.980000e-34,1.898572,-8.090899,1.640000e-13,-0.732581,18.605042,8.540000e-75,2.631153,SPCS3,-0.364005
28,SPTSSA,-12.394666,8.300000e-33,-5.902274,-10.981855,1.320000e-25,-3.347373,-11.095546,3.930000e-26,-3.428758,...,2.530000e-10,-1.086156,-9.308602,3.680000e-18,-0.818911,-1.976134,1.000000e+00,-0.267244,SPTSSA,-0.046242
29,SYVN1,-4.778501,3.938330e-04,-2.381352,-4.074815,1.008515e-02,-1.236120,-5.320935,2.620000e-05,-1.658671,...,1.848883e-02,0.625388,-4.193312,6.652845e-03,-0.374444,6.882185,1.570000e-09,0.999831,SYVN1,0.200588
30,TLN1,-6.275900,8.380000e-08,-3.409051,-1.633664,1.000000e+00,-0.482074,-1.197631,1.000000e+00,-0.300960,...,2.310000e-124,3.670848,1.868013,1.000000e+00,0.163297,24.845935,8.530000e-134,3.507551,TLN1,-0.002740
33,WDR82,-13.632659,7.680000e-40,-6.310832,-14.445497,7.890000e-45,-4.457126,-9.678487,1.090000e-19,-3.056644,...,1.400000e-05,0.878680,-18.957454,1.150000e-77,-1.690365,17.614380,5.560000e-67,2.569045,WDR82,-0.157223
34,ZAP70,-5.622698,4.380000e-06,-2.430853,-6.742112,3.840000e-09,-2.065508,-5.529092,8.270000e-06,-1.741270,...,2.560000e-75,2.890842,1.129669,1.000000e+00,0.091033,19.546962,1.280000e-82,2.799809,ZAP70,-0.352628

In [43]:
strict_filtered_genes.to_csv('validation/cripser/T_cell_exhaustion/strict_filtered_genes_with_diffex.csv', index=False)